#!/usr/bin/python
import os
import sys
import re
import timeit
import json


def gather_version():
	args_file = sys.argv[1]
        args_data = file(args_file).read()
	try:
		args = args_data.split("=")	
		if (args[0] == "name"): path_to_log = args[1]
		jboss_logfile = open(path_to_log,"r")
		res = 0
		while not res:
			test_str = jboss_logfile.readline()
			re_str = "JBAS\d{6}\:\s(.*?)\sstarting"
			regex = re.compile(re_str)
			res = regex.search(test_str)
		if res:
			print json.dumps({"failed" : False, "version" : res.group(1).strip(), "changed" : True})
			dbgfile = open("/tmp/vers","w")
			dbgfile.write(res.group(1).strip())
		else:
			print json.dumps({"error" : "Version not found or not a Jboss log", "failed" : True})
	except: 
		print json.dumps({"error" : "Error while logfile reading", "failed" : True})

gather_version()
